// Service Worker — minimal cache strategy
// Generated by build.js with versioned CACHE_NAME

const CACHE_NAME = '__CACHE_VERSION__';
const PRECACHE = [
    '/',
    '/index.html',
    '/static/css/main.css',
    '/static/js/scripts.js',
    '/static/assets/img/photo.webp',
    '/static/assets/img/photo.jfif',
    '/static/assets/favicon-32.png',
    '/manifest.json',
    '/publications.bib',
];

self.addEventListener('install', e => {
    e.waitUntil(
        caches.open(CACHE_NAME)
            .then(c => c.addAll(PRECACHE))
            .then(() => self.skipWaiting())
    );
});

self.addEventListener('activate', e => {
    e.waitUntil(
        caches.keys()
            .then(keys => Promise.all(keys.filter(k => k !== CACHE_NAME).map(k => caches.delete(k))))
            .then(() => self.clients.claim())
    );
});

self.addEventListener('fetch', e => {
    if (e.request.method !== 'GET') return;
    const url = new URL(e.request.url);
    // Only same-origin requests
    if (url.origin !== self.location.origin) return;

    // Network-first for HTML (always fresh content, fallback to cache offline)
    if (e.request.mode === 'navigate' || url.pathname === '/' || url.pathname.endsWith('.html')) {
        e.respondWith(
            fetch(e.request)
                .then(res => {
                    const copy = res.clone();
                    caches.open(CACHE_NAME).then(c => c.put(e.request, copy));
                    return res;
                })
                .catch(() => caches.match(e.request).then(c => c || caches.match('/index.html')))
        );
        return;
    }

    // Cache-first for static assets
    e.respondWith(
        caches.match(e.request).then(cached => cached || fetch(e.request).then(res => {
            // Only cache successful responses
            if (res.status === 200) {
                const copy = res.clone();
                caches.open(CACHE_NAME).then(c => c.put(e.request, copy));
            }
            return res;
        }))
    );
});
