title: Sang Min Lee's Homepage
page-top-title: Sang Min Lee
top-section-bg-text: AI for Resilient Infrastructure
home-subtitle: Sang Min Lee&ensp;|&ensp;이상민
copyright-text: '&copy; Sang Min Lee 2024-2026. All Rights Reserved.'
