title: Sang Min Lee
page-top-title: Sang Min Lee
top-section-bg-text: AI for Resilient Infrastructure
home-subtitle: Sang Min Lee | Seoul National University
copyright-text: '&copy; 2026 Sang Min Lee. All Rights Reserved.'
